# Generated by Django 5.1.2 on 2024-11-04 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-title"]},
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["-title"], name="book_book_title_ee4b12_idx"),
        ),
    ]
