# Generated by Django 5.1.2 on 2024-11-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_options_book_book_book_title_ee4b12_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrating",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_ratings",
                to="book.book",
            ),
        ),
    ]
