# Generated by Django 5.1.2 on 2024-11-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_bookrating_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
    ]
